Repository Iltotore/iron, pull requests merged in 2022-12, with the labels that each got.

#68 cats: add refineEither* methods
  build.sc
  cats/src/io/github/iltotore/iron/cats.scala
  examples/catsValidation/src/io/github/iltotore/iron/catsValidation/Main.scala
  examples/catsValidation/src/io/github/iltotore/iron/catsValidation/README.md
  examples/formCats/src/io/github/iltotore/iron/formCats/HttpServer.scala
  examples/formCats/src/io/github/iltotore/iron/formCats/Main.scala
Labels: enhancement, breaking changes

#79 Add constraint for non-blank strings
  main/src/io/github/iltotore/iron/constraint/string.scala
  main/test/src/io/github/iltotore/iron/testing/StringSuite.scala
Labels: enhancement

#90 feat: Add common char constraints
  main/src/io/github/iltotore/iron/constraint/all.scala
  main/src/io/github/iltotore/iron/constraint/char.scala
  main/src/io/github/iltotore/iron/constraint/collection.scala
  main/src/io/github/iltotore/iron/constraint/string.scala
  main/src/io/github/iltotore/iron/conversion.scala
  main/test/src/io/github/iltotore/iron/testing/CharSuite.scala
  main/test/src/io/github/iltotore/iron/testing/CollectionSuite.scala
  main/test/src/io/github/iltotore/iron/testing/StringSuite.scala
Labels: breaking changes
